// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using db;

#nullable disable

namespace main.Migrations
{
    [DbContext(typeof(RimeDbContext))]
    [Migration("20241002094811_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("model.KV", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("kI64")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kStr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("kType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("vF64")
                        .HasColumnType("REAL");

                    b.Property<long?>("vI64")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vStr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("bl");

                    b.HasIndex("ct");

                    b.HasIndex("kDesc");

                    b.HasIndex("kI64");

                    b.HasIndex("kStr");

                    b.HasIndex("ut");

                    b.ToTable("KV");
                });
#pragma warning restore 612, 618
        }
    }
}
